import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Header
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.cv': 'CV',
    'nav.projects': 'Projets',
    'nav.contact': 'Contact',

    // Home
    'home.hero.title': 'Bienvenue sur mon site',
    'home.hero.name': 'Alexandre Pinguin',
    'home.hero.subtitle': 'Étudiant en Troisième année de BUT Réseaux et Télécommunications - Parcours cybersécurité',
    'home.hero.cta1': 'Découvrir mon profil',
    'home.hero.cta2': 'Voir mes projets',
    'home.features.title': "Mes domaines d'intérêt",
    'home.features.network.title': 'Réseaux',
    'home.features.network.desc': 'Conception, déploiement et sécurisation d\'infrastructures réseau : VLANs, routage, pare-feux pfSense et services réseau (DHCP, DNS, SSH).',
    'home.features.security.title': 'Cybersécurité',
    'home.features.security.desc': 'Sensibilisation, audit de sécurité, chiffrement, pentesting et mise en place de politiques de protection des systèmes d\'information.',
    'home.features.dev.title': 'Administration Système',
    'home.features.dev.desc': 'Gestion de serveurs Linux et Windows, déploiement de services (Samba, Moodle, monitoring), scripting et automatisation des tâches.',
    'home.cta.title': 'Ouvert aux opportunités',
    'home.cta.desc': "Actuellement à la recherche d'une alternance ou d'un stage en tant que technicien/administrateur réseaux ou responsable sécurité des systèmes d'information. N'hésitez pas à me contacter !",
    'home.cta.button': 'Me contacter',

    // About
    'about.title': 'À propos de moi',
    'about.subtitle': 'Étudiant passionné en Réseaux et Télécommunications',
    'about.parcours.title': 'Mon parcours',
    'about.parcours.desc': "Après un baccalauréat STL, je me suis orienté vers le BUT Réseaux et Télécommunications à l'IUT de La Réunion. Cette reconversion réussie me permet d'allier ma curiosité scientifique à ma passion pour l'informatique et les réseaux.",
    'about.motivation.title': 'Ma motivation',
    'about.motivation.desc': "Je suis motivé par le désir constant d'apprendre et de me perfectionner dans le domaine des télécommunications et de la cybersécurité. Chaque projet est une nouvelle opportunité de développer mes compétences.",
    'about.passions.title': 'Mes passions',
    'about.passions.gaming.title': 'Jeux vidéo',
    'about.passions.gaming.desc': "Passionné par l'univers du gaming, je m'intéresse aux technologies derrière les jeux et aux communautés en ligne.",
    'about.passions.social.title': 'Réseaux sociaux',
    'about.passions.social.desc': "Créateur de contenu sur différentes plateformes, j'explore les tendances numériques et la communication digitale.",
    'about.passions.sports.title': 'Sport',
    'about.passions.sports.desc': "Le sport m'aide à maintenir un équilibre de vie sain et développe mon esprit d'équipe et ma persévérance.",
    'about.passions.science.title': 'Sciences',
    'about.passions.science.desc': "Mon parcours en STL m'a donné un goût prononcé pour les sciences, la chimie et l'expérimentation.",
    'about.passions.fashion.title': 'Mode',
    'about.passions.fashion.desc': "Intéressé par le monde de la mode, j'ai participé à l'élection de Mister Étudiant Réunion 2026, une expérience qui me permet de développer mon côté humain et ma confiance en moi.",
    'about.passions.dance.title': 'Danse',
    'about.passions.dance.desc': "La danse est une passion qui me permet de m'exprimer, de me dépasser et de partager des moments de convivialité.",
    'about.qualities.title': 'Mes qualités',
    'about.qualities.team.title': "Esprit d'équipe",
    'about.qualities.team.desc': 'Collaboration efficace et écoute active au sein des projets de groupe.',
    'about.qualities.organized.title': 'Organisé',
    'about.qualities.organized.desc': 'Planification rigoureuse et gestion efficace du temps et des ressources.',
    'about.qualities.curious.title': 'Curieux',
    'about.qualities.curious.desc': "Toujours en quête de nouvelles connaissances et technologies à explorer.",
    'about.qualities.adaptable.title': 'Adaptable',
    'about.qualities.adaptable.desc': "Capacité à m'ajuster rapidement aux nouvelles situations et défis.",

       // CV
    'cv.title': 'ALEXANDRE PINGUIN',
    'cv.subtitle': 'Alternant Infrastructures IT (Support, Systèmes, Réseaux, Sécurité)',
    'cv.download': 'Télécharger mon CV',
 
    'cv.profile.title': 'PROFIL',
    'cv.profile.desc': "Étudiant motivé en BUT Réseaux & Télécommunications, passionné par les systèmes et les réseaux grâce à mes différents projets, organisé, rigoureux et en réorientation réussie après un bac STL. Je recherche une alternance en tant que Technicien ou Administrateur Systèmes, Réseaux & Sécurité pour renforcer mes compétences sur les infrastructures en entreprise.",
    'cv.profile.extra': 'Permis B – Véhiculé · Saint-Louis',
 
    'cv.qualities.title': 'QUALITÉS',
    'cv.quality.1': "Sens de l'organisation",
    'cv.quality.2': 'Capacité à documenter et à transmettre',
    'cv.quality.3': 'Polyvalent',
    'cv.quality.4': 'Autonome',
 
    'cv.languages.title': 'LANGUES',
    'cv.lang.french': 'Français',
    'cv.lang.french.badge': 'Langue maternelle',
    'cv.lang.french.level': 'Courant',
    'cv.lang.english': 'Anglais technique',
    'cv.lang.english.level': 'Lecture de documentations et bases de données',
    'cv.lang.spanish': 'Espagnol',
    'cv.lang.spanish.level': 'Débutant',
 
    'cv.software.title': 'COMPÉTENCES TECHNIQUES',
    'cv.tech.network.title': 'Réseaux & Sécurité :',
    'cv.tech.network.desc': 'TCP/IP, VLANs, pfSense, routage, DHCP, DNS, audit de sécurité, pare-feu Stormshield, Wireshark, Packet Tracer, Proxmox/VMware et Zabbix',
    'cv.tech.systems.title': 'Systèmes & Virtualisation :',
    'cv.tech.systems.desc': 'Windows Server, Linux (Ubuntu/Debian), Hyper-V, VirtualBox, Raspberry Pi, Proxmox/VMware',
    'cv.tech.admin.title': 'Administration :',
    'cv.tech.admin.desc': 'TeamViewer, Splashtop, AnyDesk, terminal distant, Active Directory, GPO',
 
    'cv.passions.title': 'PASSIONS',
    'cv.passion.1': 'Jeux vidéo',
    'cv.passion.2': 'Réseaux sociaux',
    'cv.passion.3': 'Mode',
    'cv.passion.4': 'Sport',
 
    'cv.diplomas.title': 'DIPLÔMES / CERTIFICATIONS',
    'cv.dipl.1.title': 'Troisième année BUT Réseaux et Télécommunications – parcours cybersécurité (en cours)',
    'cv.dipl.1.school': 'IUT de la Réunion',
    'cv.dipl.2.title': 'Bac STL (Sciences et Technologies de Laboratoire)',
    'cv.dipl.2.school': 'Lycée général et technologique Antoine Roussin, Saint-Louis',
    'cv.dipl.3.title': 'Certification Pix',
    'cv.dipl.3.school': 'Lycée général et technologique Antoine Roussin, Saint-Louis',
    'cv.dipl.4.title': 'Attestation de suivi ANSSI',
    'cv.dipl.4.school': 'IUT de la Réunion, Saint-Pierre',
 
    'cv.internship.title': 'STAGE – ADMINISTRATEUR SYSTÈMES, RÉSEAUX & SÉCURITÉ',
    'cv.internship.company': 'MRI RUN · 2 mois',
    'cv.internship.1.title': 'SuperOps',
    'cv.internship.1.desc': "Formation approfondie et utilisation courante de la solution RMM/PSA pour la supervision automatisée, la gestion de parc et le monitoring des infrastructures. Déploiement de différents scripts d'automatisation pour plusieurs tâches (renommage de poste, déploiement d'OpenVPN Connect).",
    'cv.internship.2.title': 'Hyper-V',
    'cv.internship.2.desc': "Administration, configuration et déploiement d'environnements virtualisés (serveurs et postes clients).",
    'cv.internship.3.title': 'Écosystème ESET',
    'cv.internship.3.desc': 'Déploiement global et gestion centralisée via ESET Protect, supervision et réponse aux incidents (EDR) avec ESET Inspect, et protection des endpoints (ESET Endpoint Antivirus).',
    'cv.internship.4.title': 'Sécurisation des accès',
    'cv.internship.4.desc': "Conception et déploiement d'une procédure d'authentification multi-facteur (MFA) via ESET Secure Authentication.",
 
    'cv.projects.title': 'PROJETS RÉSEAUX ACADÉMIQUES',
    'cv.projects.1.title': 'Concevoir un réseau sécurisé',
    'cv.projects.1.desc': "Ce projet vise à concevoir, déployer et sécuriser l'architecture réseau d'une entreprise multisite. L'objectif principal est d'assurer la disponibilité des services critiques, la confidentialité des données et l'intégrité des flux, en adéquation avec les normes de l'ANSSI.",
    'cv.projects.2.title': 'Audit de sécurité réseau direct',
    'cv.projects.2.desc': "Rédaction complète d'un audit de sécurité pour un client en effectuant du pentesting sur plusieurs machines.",
    'cv.projects.3.title': 'Infrastructure réseau complète',
    'cv.projects.3.desc': "Création d'un réseau inter-sites (maison mère/succursale) avec pfSense et switches VLAN. Mise en place de serveurs Samba (partage de fichiers) et Moodle (plateforme e-learning). Attribution dynamique des IP par DHCP, filtrage via règles firewall.",
 
    'cv.future.title': 'PROJET PROFESSIONNEL',
    'cv.future.desc': "Je recherche une alternance en Infrastructures IT (support, systèmes, réseaux, sécurité) pour mettre en pratique mes compétences et poursuivre ma progression vers la cybersécurité.",
    
    // Projects
    'projects.title': 'Mes Projets',
    'projects.subtitle': 'Découvrez les projets que j\'ai réalisés durant ma formation en Réseaux et Télécommunications',
    'projects.academic': 'Projet réalisé',
    'projects.view': 'Voir la présentation',
    'projects.skills.title': 'Compétences développées',
    'projects.skills.desc': 'Ces projets m\'ont permis de développer mes compétences techniques et pratiques dans des domaines variés des télécommunications et de la cybersécurité.',
    'projects.skills.network': 'Réseaux',
    'projects.skills.network.desc': 'Configuration et sécurisation',
    'projects.skills.security': 'Sécurité',
    'projects.skills.security.desc': 'Chiffrement et protection',
    'projects.skills.monitoring': 'Monitoring',
    'projects.skills.monitoring.desc': 'Surveillance et alertes',
    'projects.skills.telecom': 'Télécom',
    'projects.skills.telecom.desc': 'Codecs et transmission',
    // Project items
    'project.cyber.title': 'Projet de sensibilisation à la cybersécurité',
    'project.cyber.desc': 'Sensibiliser le public aux bonnes pratiques de sécurité.',
    'project.cyber.details': 'Ce projet vise à éduquer et sensibiliser les utilisateurs aux menaces de cybersécurité actuelles et aux mesures préventives essentielles pour protéger leurs données personnelles et professionnelles.',
    'project.MFA.title': 'Stage chez MRI RUN – Déploiement ESET et MFA',
    'project.MFA.desc': 'Déploiement et gestion centralisée de la solution de sécurité ESET, avec mise en place d\'une authentification multi-facteur (MFA) pour sécuriser les accès',
    'project.MFA.details': 'ESET Protect pour la gestion centralisée, ESET Inspect (EDR) pour la supervision et la réponse aux incidents, ESET Endpoint Antivirus pour la protection des postes, et ESET Secure Authentication pour le MFA.',
    'project.temp.title': 'Système de surveillance de la température pour salle des serveurs',
    'project.temp.desc': 'Ce projet vise à concevoir et déployer un appareil de mesure de la température pour une salle des serveurs, permettant une surveillance en temps réel des températures.',
    'project.temp.details': 'Développement d\'un système de monitoring utilisant des capteurs de température connectés pour assurer la surveillance continue et l\'alerte en cas de dépassement des seuils critiques.',
    'project.crypto.title': 'Exploration de solutions de chiffrement sous Linux : Gocryptfs et LUKS',
    'project.crypto.desc': 'Ce projet explore et compare deux méthodes de chiffrement sous Linux, Gocryptfs et LUKS, en examinant leurs avantages, inconvénients, cas d\'utilisation, et performances.',
    'project.crypto.details': 'Analyse comparative approfondie des solutions de chiffrement, incluant des tests de performance, d\'usabilité et de sécurité pour guider le choix selon les besoins spécifiques.',
    'project.network.title': 'Construire un réseau informatique pour une petite structure',
    'project.network.desc': 'Ce projet consiste à déployer un réseau informatique sécurisé pour une petite entreprise immobilière, incluant des VLANs, une DMZ, des services réseau (HTTP, FTP, DHCP, SSH), un pare-feu pfSense et un accès Internet.',
    'project.network.details': 'Conception et implémentation complète d\'une infrastructure réseau sécurisée avec segmentation, services réseau et documentation technique détaillée.',
    'project.telecom.title': 'Caractériser et mesurer un système Télécom',
    'project.telecom.desc': 'L\'objectif de ce projet était d\'expérimenter un codec (G.711) dans un système télécom.',
    'project.telecom.details': 'Étude pratique des codecs audio dans les télécommunications, analyse des performances et de la qualité de transmission du codec G.711 dans différentes conditions.',
    'project.supervision.title': 'Supervision des performances réseau',
    'project.supervision.desc': 'Le projet consiste à mettre en place une console de supervision permettant de surveiller l\'état des équipements réseau, avoir un historique des pannes sur les deux derniers mois et envoyer des alertes en cas de panne prolongée.',
    'project.supervision.details': 'Développement d\'une solution de monitoring réseau complète avec tableau de bord, historique des incidents et système d\'alertes automatisées pour une maintenance proactive.',
    'project.safescreen.title': 'Projet SafeScreen',
    'project.safescreen.desc': 'Création d\'un réseau d\'écrans de divertissement destiné aux résidents d\'un EHPAD, offrant un accès sécurisé à des contenus adaptés pour améliorer leur quotidien.',
    'project.safescreen.details': 'Dans le cadre de ce projet, j\'ai été en charge de la partie cybersécurité : sécurisation du réseau d\'écrans, mise en place de contrôles d\'accès, protection des données des résidents et définition des politiques de sécurité pour garantir un environnement numérique fiable et conforme.',
    'project.integratif.title': 'Projet intégratif – Architecture multi-sites',
    'project.integratif.desc': 'Mise en place d\'une architecture réseau complète répartie sur deux sites (Maison Mère et Succursale), interconnectés via pfSense avec segmentation par VLANs.',
    'project.integratif.details': 'Déploiement d\'une infrastructure multi-sites comprenant des VLANs par catégorie d\'utilisateurs (administration, professeurs, étudiants), un serveur Samba pour le partage de fichiers et un serveur Moodle accessible depuis l\'ensemble des réseaux, le tout sécurisé par des pare-feux pfSense.',
    'project.iutfam.title': 'Site web IUTFAM – Réseau social étudiant',
    'project.iutfam.desc': 'Conception et développement d\'un réseau social web dédié aux étudiants de l\'IUT de La Réunion, permettant la communication et l\'échange au sein de la communauté étudiante.',
    'project.iutfam.details': 'Ce projet collaboratif avait pour défi de créer une plateforme sociale complète avec système de chat, gestion d\'événements et espace communautaire, offrant aux étudiants de l\'IUT un outil de communication dédié et sécurisé.',

    // Contact
    'contact.title': 'Me Contacter',
    'contact.subtitle': "N'hésitez pas à me contacter pour toute question, collaboration ou opportunité professionnelle",
    'contact.info.title': 'Informations de contact',
    'contact.phone': 'Téléphone',
    'contact.location': 'Localisation',
    'contact.form.name': 'Nom complet',
    'contact.form.name.placeholder': 'Votre nom',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subject.placeholder': 'Sujet de votre message',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Écrivez votre message ici...',
    'contact.form.send': 'Envoyer le message',
    'contact.form.title': 'Envoyez-moi un message',
    'contact.form.required': '* Champs obligatoires',
    'contact.form.error.title': 'Erreur',
    'contact.form.error.desc': 'Veuillez remplir tous les champs obligatoires.',
    'contact.form.success.title': 'Message envoyé !',
    'contact.form.success.desc': 'Merci pour votre message. Je vous répondrai dans les plus brefs délais.',
    'contact.available.title': 'Disponibilité',
    'contact.available.desc': "Je suis actuellement étudiant en Troisième année de BUT Réseaux et Télécommunications et je suis ouvert aux opportunités d'alternance et de stage.",
    'contact.available.best': 'Meilleur moment pour me contacter :',
    'contact.available.hours': 'Lundi - Vendredi : 9h00 - 18h00',
    'contact.available.response': 'Réponse sous 24-48h',
    'contact.connect': 'Restons connectés !',
    'contact.connect.desc': "Je suis toujours intéressé par de nouveaux projets, des collaborations et des opportunités d'apprentissage dans le domaine des réseaux et télécommunications. N'hésitez pas à me contacter !",
    'contact.tag.student': 'Étudiant motivé',
    'contact.tag.tech': 'Passionné de tech',
    'contact.tag.open': 'Ouvert aux opportunités',
    'contact.form.error.send': "Le message n'a pas pu être envoyé. Réessayez ou écrivez-moi directement par mail.",
    'contact.form.sending': 'Envoi en cours…',

    // Footer
    'footer.role': 'Étudiant en Réseaux & Télécommunications',
    'footer.rights': '© Alexandre Pinguin. Tous droits réservés.',

    // Project modal
    'projects.modal.close': 'Fermer',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.cv': 'Resume',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',

    // Home
    'home.hero.title': 'Welcome to my website',
    'home.hero.name': 'Alexandre Pinguin',
    'home.hero.subtitle': 'Third-year student in Networks & Telecommunications – Cybersecurity track',
    'home.hero.cta1': 'Discover my profile',
    'home.hero.cta2': 'View my projects',
    'home.features.title': 'My areas of interest',
    'home.features.network.title': 'Networks',
    'home.features.network.desc': 'Design, deployment and security of network infrastructures: VLANs, routing, pfSense firewalls and network services (DHCP, DNS, SSH).',
    'home.features.security.title': 'Cybersecurity',
    'home.features.security.desc': 'Awareness, security audits, encryption, pentesting and implementation of information systems protection policies.',
    'home.features.dev.title': 'System Administration',
    'home.features.dev.desc': 'Linux and Windows server management, service deployment (Samba, Moodle, monitoring), scripting and task automation.',
    'home.cta.title': 'Open to opportunities',
    'home.cta.desc': 'Currently looking for an apprenticeship or internship as a network technician/administrator or information security officer. Feel free to contact me!',
    'home.cta.button': 'Contact me',

    // About
    'about.title': 'About me',
    'about.subtitle': 'Passionate student in Networks & Telecommunications',
    'about.parcours.title': 'My background',
    'about.parcours.desc': 'After a STL baccalaureate, I moved into Networks & Telecommunications at IUT de La Réunion. This successful transition allows me to combine my scientific curiosity with my passion for IT and networks.',
    'about.motivation.title': 'My motivation',
    'about.motivation.desc': 'I am driven by a constant desire to learn and improve in the field of telecommunications and cybersecurity. Every project is a new opportunity to develop my skills.',
    'about.passions.title': 'My passions',
    'about.passions.gaming.title': 'Video games',
    'about.passions.gaming.desc': 'Passionate about the gaming universe, I am interested in the technologies behind games and online communities.',
    'about.passions.social.title': 'Social media',
    'about.passions.social.desc': 'Content creator on various platforms, I explore digital trends and digital communication.',
    'about.passions.sports.title': 'Sports',
    'about.passions.sports.desc': 'Sports help me maintain a healthy life balance and develop my teamwork spirit and perseverance.',
    'about.passions.science.title': 'Sciences',
    'about.passions.science.desc': 'My STL background gave me a strong taste for science, chemistry, and experimentation.',
    'about.passions.fashion.title': 'Fashion',
    'about.passions.fashion.desc': 'Interested in the fashion world, I participated in the Mister Student Réunion 2026 election, an experience that allows me to develop my human side and self-confidence.',
    'about.passions.dance.title': 'Dance',
    'about.passions.dance.desc': 'Dance is a passion that allows me to express myself, push my limits, and share moments of togetherness.',
    'about.qualities.title': 'My qualities',
    'about.qualities.team.title': 'Team spirit',
    'about.qualities.team.desc': 'Effective collaboration and active listening within group projects.',
    'about.qualities.organized.title': 'Organized',
    'about.qualities.organized.desc': 'Rigorous planning and effective time and resource management.',
    'about.qualities.curious.title': 'Curious',
    'about.qualities.curious.desc': 'Always seeking new knowledge and technologies to explore.',
    'about.qualities.adaptable.title': 'Adaptable',
    'about.qualities.adaptable.desc': 'Ability to quickly adjust to new situations and challenges.',

      // CV
    'cv.title': 'ALEXANDRE PINGUIN',
    'cv.subtitle': 'Work-Study IT Infrastructure (Support, Systems, Networks, Security)',
    'cv.download': 'Download my resume',
 
    'cv.profile.title': 'PROFILE',
    'cv.profile.desc': "Motivated Networks & Telecommunications student, passionate about systems and networks through my various projects, organized, rigorous, with a successful change of path after a STL baccalaureate. I am looking for a work-study position (apprenticeship) as a Systems, Networks & Security Technician or Administrator to strengthen my skills on enterprise infrastructures.",
    'cv.profile.extra': 'Driving licence (B) – Own vehicle · Saint-Louis',
 
    'cv.qualities.title': 'QUALITIES',
    'cv.quality.1': 'Organizational skills',
    'cv.quality.2': 'Ability to document and share knowledge',
    'cv.quality.3': 'Versatile',
    'cv.quality.4': 'Autonomous',
 
    'cv.languages.title': 'LANGUAGES',
    'cv.lang.french': 'French',
    'cv.lang.french.badge': 'Native',
    'cv.lang.french.level': 'Fluent',
    'cv.lang.english': 'Technical English',
    'cv.lang.english.level': 'Reading documentation and databases',
    'cv.lang.spanish': 'Spanish',
    'cv.lang.spanish.level': 'Beginner',
 
    'cv.software.title': 'TECHNICAL SKILLS',
    'cv.tech.network.title': 'Networks & Security:',
    'cv.tech.network.desc': 'TCP/IP, VLANs, pfSense, routing, DHCP, DNS, security audit, Stormshield firewall, Wireshark, Packet Tracer, Proxmox/VMware and Zabbix',
    'cv.tech.systems.title': 'Systems & Virtualization:',
    'cv.tech.systems.desc': 'Windows Server, Linux (Ubuntu/Debian), Hyper-V, VirtualBox, Raspberry Pi, Proxmox/VMware',
    'cv.tech.admin.title': 'Administration:',
    'cv.tech.admin.desc': 'TeamViewer, Splashtop, AnyDesk, remote terminal, Active Directory, GPO',
 
    'cv.passions.title': 'PASSIONS',
    'cv.passion.1': 'Video games',
    'cv.passion.2': 'Social media',
    'cv.passion.3': 'Fashion',
    'cv.passion.4': 'Sport',
 
    'cv.diplomas.title': 'EDUCATION / CERTIFICATIONS',
    'cv.dipl.1.title': "Third year of the BUT Networks and Telecommunications – Cybersecurity track (ongoing)",
    'cv.dipl.1.school': 'IUT de la Réunion',
    'cv.dipl.2.title': 'STL Baccalaureate (Laboratory Science and Technology)',
    'cv.dipl.2.school': 'Lycée général et technologique Antoine Roussin, Saint-Louis',
    'cv.dipl.3.title': 'Pix Certification',
    'cv.dipl.3.school': 'Lycée général et technologique Antoine Roussin, Saint-Louis',
    'cv.dipl.4.title': 'ANSSI Training Certificate',
    'cv.dipl.4.school': 'IUT de la Réunion, Saint-Pierre',
 
    'cv.internship.title': 'INTERNSHIP – SYSTEMS, NETWORKS & SECURITY ADMINISTRATOR',
    'cv.internship.company': 'MRI RUN · 2 months',
    'cv.internship.1.title': 'SuperOps',
    'cv.internship.1.desc': 'In-depth training and daily use of the RMM/PSA solution for automated monitoring, fleet management and infrastructure monitoring. Deployment of automation scripts for several tasks (computer renaming, OpenVPN Connect deployment).',
    'cv.internship.2.title': 'Hyper-V',
    'cv.internship.2.desc': 'Administration, configuration and deployment of virtualized environments (servers and client workstations).',
    'cv.internship.3.title': 'ESET ecosystem',
    'cv.internship.3.desc': 'Global deployment and centralized management with ESET Protect, incident monitoring and response (EDR) with ESET Inspect, and endpoint protection (ESET Endpoint Antivirus).',
    'cv.internship.4.title': 'Access security',
    'cv.internship.4.desc': 'Design and deployment of a multi-factor authentication (MFA) procedure using ESET Secure Authentication.',
 
    'cv.projects.title': 'ACADEMIC NETWORK PROJECTS',
    'cv.projects.1.title': 'Designing a secure network',
    'cv.projects.1.desc': "This project aims to design, deploy and secure the network architecture of a multi-site company. The main goal is to ensure the availability of critical services, data confidentiality and traffic integrity, in line with ANSSI standards.",
    'cv.projects.2.title': 'Direct network security audit',
    'cv.projects.2.desc': 'Complete writing of a security audit for a client by performing pentesting on several machines.',
    'cv.projects.3.title': 'Complete network infrastructure',
    'cv.projects.3.desc': 'Creation of an inter-site network (headquarters/branch) with pfSense and VLAN switches. Setup of Samba (file sharing) and Moodle (e-learning platform) servers. Dynamic IP assignment via DHCP, filtering through firewall rules.',
 
    'cv.future.title': 'CAREER GOAL',
    'cv.future.desc': 'I am looking for a work-study position in IT Infrastructure (support, systems, networks, security) to apply my skills and keep progressing towards cybersecurity.',

    // Projects
    'projects.title': 'My Projects',
    'projects.subtitle': 'Discover the projects I completed during my Networks & Telecommunications studies',
    'projects.academic': 'Completed project',
    'projects.view': 'View presentation',
    'projects.skills.title': 'Skills developed',
    'projects.skills.desc': 'These projects allowed me to develop my technical and practical skills in various areas of telecommunications and cybersecurity.',
    'projects.skills.network': 'Networks',
    'projects.skills.network.desc': 'Configuration and security',
    'projects.skills.security': 'Security',
    'projects.skills.security.desc': 'Encryption and protection',
    'projects.skills.monitoring': 'Monitoring',
    'projects.skills.monitoring.desc': 'Surveillance and alerts',
    'projects.skills.telecom': 'Telecom',
    'projects.skills.telecom.desc': 'Codecs and transmission',
    // Project items
    'project.cyber.title': 'Cybersecurity Awareness Project',
    'project.cyber.desc': 'Raising public awareness of security best practices.',
    'project.cyber.details': 'This project aims to educate and raise awareness among users about current cybersecurity threats and essential preventive measures to protect their personal and professional data.',
    'project.MFA.title': 'Internship at MRI RUN – ESET Deployment and MFA',
    'project.MFA.desc': 'Deployment and centralized management of the ESET security solution, including the setup of multi-factor authentication (MFA) to secure access.',
    'project.MFA.details': 'ESET Protect for centralized management, ESET Inspect (EDR) for monitoring and incident response, ESET Endpoint Antivirus for endpoint protection, and ESET Secure Authentication for MFA.',
    'project.temp.title': 'Server Room Temperature Monitoring System',
    'project.temp.desc': 'This project aims to design and deploy a temperature measurement device for a server room, enabling real-time temperature monitoring.',
    'project.temp.details': 'Development of a monitoring system using connected temperature sensors to ensure continuous monitoring and alerts when critical thresholds are exceeded.',
    'project.crypto.title': 'Exploring Linux Encryption Solutions: Gocryptfs and LUKS',
    'project.crypto.desc': 'This project explores and compares two Linux encryption methods, Gocryptfs and LUKS, examining their advantages, disadvantages, use cases, and performance.',
    'project.crypto.details': 'In-depth comparative analysis of encryption solutions, including performance, usability, and security tests to guide the choice according to specific needs.',
    'project.network.title': 'Building a Computer Network for a Small Business',
    'project.network.desc': 'This project involves deploying a secure computer network for a small real estate company, including VLANs, a DMZ, network services (HTTP, FTP, DHCP, SSH), a pfSense firewall, and Internet access.',
    'project.network.details': 'Complete design and implementation of a secure network infrastructure with segmentation, network services, and detailed technical documentation.',
    'project.telecom.title': 'Characterizing and Measuring a Telecom System',
    'project.telecom.desc': 'The objective of this project was to experiment with a codec (G.711) in a telecom system.',
    'project.telecom.details': 'Practical study of audio codecs in telecommunications, analyzing the performance and transmission quality of the G.711 codec under different conditions.',
    'project.supervision.title': 'Network Performance Monitoring',
    'project.supervision.desc': 'The project involves setting up a monitoring console to monitor the status of network equipment, maintain a two-month outage history, and send alerts for prolonged outages.',
    'project.supervision.details': 'Development of a complete network monitoring solution with dashboard, incident history, and automated alert system for proactive maintenance.',
    'project.safescreen.title': 'SafeScreen Project',
    'project.safescreen.desc': 'Creation of an entertainment screen network for nursing home residents, providing secure access to adapted content to improve their daily lives.',
    'project.safescreen.details': 'In this project, I was in charge of the cybersecurity part: securing the screen network, implementing access controls, protecting resident data, and defining security policies to ensure a reliable and compliant digital environment.',
    'project.integratif.title': 'Integrative Project – Multi-site Architecture',
    'project.integratif.desc': 'Setting up a complete network architecture across two sites (Headquarters and Branch), interconnected via pfSense with VLAN segmentation.',
    'project.integratif.details': 'Deployment of a multi-site infrastructure including VLANs per user category (administration, professors, students), a Samba file-sharing server, and a Moodle server accessible from all networks, all secured by pfSense firewalls.',
    'project.iutfam.title': 'IUTFAM Website – Student Social Network',
    'project.iutfam.desc': 'Design and development of a web-based social network dedicated to IUT de La Réunion students, enabling communication and exchange within the student community.',
    'project.iutfam.details': 'This collaborative project aimed to create a complete social platform with chat system, event management, and community space, providing IUT students with a dedicated and secure communication tool.',

    // Contact
    'contact.title': 'Contact Me',
    'contact.subtitle': 'Feel free to contact me for any questions, collaboration or professional opportunities',
    'contact.info.title': 'Contact information',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.form.name': 'Full name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'Subject of your message',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Write your message here...',
    'contact.form.send': 'Send message',
    'contact.form.title': 'Send me a message',
    'contact.form.required': '* Required fields',
    'contact.form.error.title': 'Error',
    'contact.form.error.desc': 'Please fill in all required fields.',
    'contact.form.success.title': 'Message sent!',
    'contact.form.success.desc': 'Thank you for your message. I will get back to you as soon as possible.',
    'contact.available.title': 'Availability',
    'contact.available.desc': 'I am currently a third-year student in the Networks and Telecommunications BUT program, and I am open to work-study opportunities.',
    'contact.available.best': 'Best time to reach me:',
    'contact.available.hours': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.available.response': 'Response within 24-48h',
    'contact.connect': 'Stay connected!',
    'contact.connect.desc': 'I am always interested in new projects, collaborations and learning opportunities in the field of networks and telecommunications. Feel free to contact me!',
    'contact.tag.student': 'Motivated student',
    'contact.tag.tech': 'Tech enthusiast',
    'contact.tag.open': 'Open to opportunities',
    'contact.form.error.send': 'The message could not be sent. Please try again or email me directly.',
    'contact.form.sending': 'Sending…',

    // Footer
    'footer.role': 'Networks & Telecommunications Student',
    'footer.rights': '© Alexandre Pinguin. All rights reserved.',

    // Project modal
    'projects.modal.close': 'Close',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
